CREATE TABLE IF NOT EXISTS WALLET(id VARCHAR(50) PRIMARY KEY, balance INT);
MERGE INTO WALLET KEY(id) VALUES ('alice',100), ('bob',50);

CREATE TABLE IF NOT EXISTS FINES(id IDENTITY PRIMARY KEY, plate VARCHAR(20), amount INT);
INSERT INTO FINES(plate,amount) VALUES ('A12345',200), ('B67890',400);
