name: Build & Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # <-- SET THIS to your App Service name exactly as in Azure (NOT the full domain)
      WEBAPP_NAME: transitx-demo
      WORKING_DIR: backend
      FINAL_JAR: app.jar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        working-directory: ${{ env.WORKING_DIR }}
        run: mvn -q -B -DskipTests package

      - name: Prepare artifact (rename)
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          cp target/*.jar ${{ env.FINAL_JAR }}
          ls -l ${{ env.FINAL_JAR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WORKING_DIR }}/${{ env.FINAL_JAR }}
          startup-command: 'java -jar ${{ env.FINAL_JAR }}'
